### ISSUE TITLE
toggle task status?

### ISSUE THREAD

**Issue by KiaraGrouwstra** [louis-thevenet/vault-tasks#31]
hi there,
thanks for writing vault-tasks!
i was thinking, one feature that might make sense for an app like this might be a keybind to toggle a task between done (`[x]`) vs not done (`[ ]`).
while the edit feature could certainly already accomplish this now, this action might just be common enough to merit a bind of its own. :)

**Comment by louis-thevenet** [comment]
Hi, thanks for using vault-tasks !
You're absolutely right, I just didn't take the time to do it, I usually open with my editor to edit tasks.
I'll add it later during the weekend =)

**Comment by louis-thevenet** [comment]
Spent way too much time fixing windows build in CI 😭 
Anyway, here it is !
